name: Build and Test Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version  # Utilisez docker-compose ici

      - name: Dormir pendant 10 secondes
        run: sleep 10s
        shell: bash

      - name: Initialiser les conteneurs
        run: |
          docker-compose up -d  # Utilisez docker-compose ici
          # Verify containers are running
          docker-compose ps  # Utilisez docker-compose ici

      - name: Vérifier l'état des conteneurs
        run: |
          echo "Liste des conteneurs en cours d'exécution:"
          docker ps
          echo "Logs des conteneurs:"
          docker-compose logs  # Utilisez docker-compose ici

      - name: Installer les dépendances Composer
        run: |
          CONTAINER_ID=$(docker-compose ps -q app || docker-compose ps -q web || docker-compose ps -q laravel)  # Utilisez docker-compose ici
          if [ -z "$CONTAINER_ID" ]; then
            echo "Error: Could not find Laravel container"
            exit 1
          fi
          docker exec $CONTAINER_ID composer install

      - name: Migrer la base de données
        run: |
          CONTAINER_ID=$(docker-compose ps -q app || docker-compose ps -q web || docker-compose ps -q laravel)  # Utilisez docker-compose ici
          docker exec $CONTAINER_ID php artisan migrate --force

      - name: Peupler la base de données
        run: |
          CONTAINER_ID=$(docker-compose ps -q app || docker-compose ps -q web || docker-compose ps -q laravel)  # Utilisez docker-compose ici
          docker exec $CONTAINER_ID php artisan db:seed --force

      - name: Migrer la base de données de test
        run: |
          CONTAINER_ID=$(docker-compose ps -q app || docker-compose ps -q web || docker-compose ps -q laravel)  # Utilisez docker-compose ici
          docker exec $CONTAINER_ID php artisan migrate --env=testing --force

      - name: Exécuter les tests Pest
        run: |
          CONTAINER_ID=$(docker-compose ps -q app || docker-compose ps -q web || docker-compose ps -q laravel)  # Utilisez docker-compose ici
          docker exec $CONTAINER_ID php artisan test --testsuite=Feature  # Exécutez les tests Pest
